### ISSUE TITLE
Test point in polygon

### ISSUE THREAD

**Issue by vilterp** [bakkemo/elm-collision#1]
Hi, cool lib! Can this be easily used to test whether a point is in a polygon? Would like to use for this: https://github.com/vilterp/elm-diagrams/issues/22

**Comment by bakkemo** [comment]
Yes. Thinking of the point as its own polygon, then the point of the polygon furthest in any direction is just the point itself. so your Mink would be (Pt, Identity). Conceptually, consider the Minkowski difference when the point is in the polygon, it's sharing a point with a point in the polygon, thus it MUST be the origin in the minkowski sum. Thus the since it's IN the polygon, the Minkowski sum contains the origin. Make sense?

**Comment by bakkemo** [comment]
Yup, as long as the polygon is convex, or broken up into convex pieces.

**Comment by vilterp** [comment]
Cool. Might be useful to have that as a helper function for those not read up on Minkowski stuff such as myself.

Also, out of curiosity, how much harder is it to do this for non-convex polygons? A completely different algorithm I assume?

**Comment by bakkemo** [comment]
I added a note at the end of the readme about it. On the second point, You
might be able to use the separating axis theorem (SAT) for your concave
shapes, but I've only seen it used after triangulation. Also, SAT performs
poorly the more verticies you have (probably another reason for
pre-tesselation). My advice would be to triangulate your polygons and use
GJK.
